In [1]:
import sys
import cv2
import numpy as np
import matplotlib.pylab as plt

In [4]:
image = cv2.imread('./images/69.jpg', cv2.IMREAD_GRAYSCALE)

In [6]:
rows, cols = image.shape

In [7]:
grayHist = np.zeros([256], np.uint64)

In [13]:
for r in range(rows):
  for c in range(cols):
    grayHist[image[r][c]] += 100

In [15]:
def render(image):
  cv2.imshow('image', image)
  cv2.waitKey()
  cv2.destroyAllWindows()

In [16]:
render(image)

O(r,c)=a∗I(r,c)+b,0≤r<H,0≤c<W

In [17]:
I = image

In [27]:
a = 3
b = 0

In [28]:
O = float(a) * I + b

In [29]:
O[O>255] = 255

In [30]:
O = np.round(O)

In [31]:
O = O.astype(np.uint8)

In [32]:
# cv2.imshow('I', I)
cv2.imshow('O', O)
cv2.waitKey()
cv2.destroyAllWindows()

In [36]:
def cal_v1(param_list: list):
  for param in param_list:
    a = param[0]
    b = param[1]
    # 线性变换
    O = float(a) * I + b
    O[O>255] = 255
    O = np.round(O)
    O = O.astype(np.uint8)
    cv2.imshow(f'a={a}, b={b}', O)
  cv2.waitKey()
  cv2.destroyAllWindows()

In [ ]:
param_list = []
param_list.append((1, 0))
param_list.append((1, 20))
param_list = set(param_list)
cal_v1(param_list)

In [85]:
def cal_v2(param_list: list, image):
  cv2.imshow('origin', image)
  for param in param_list:
    L = param[0]
    H = param[1]
    # 白色更白，黑色更黑
    O = np.copy(image)
    assert id(O) != id(I)
    O[O>=H] = 255
    O[O<=L] = 0
    # O = np.round(O)
    O = O.astype(np.uint8)
    cv2.imshow(f'L={L}, H={H}', O)
  cv2.waitKey()
  cv2.destroyAllWindows()

In [86]:
param_list = []
param_list.append((0, 255))
param_list.append((50, 230))
param_list = set(param_list)
image = cv2.imread('./images/69.jpg', cv2.IMREAD_GRAYSCALE)
cal_v2(param_list, image)

In [2]:
def cal_v3(param_list: list, image):
  """伽马变换"""
  cv2.imshow('origin', image)
  for param in param_list:
    fI = image / 255.0
    gamma = param[0] # 0.3
    O = np.power(fI, gamma)
    # O = O.astype(np.uint8)
    print(O)
    cv2.imshow(f'gamma: {gamma}', O)
  cv2.waitKey()
  cv2.destroyAllWindows()

In [4]:
param_list = []
# param_list.append((0.3, ))
# param_list.append((0.6, ))
param_list.append((2.5, ))
# param_list.append((3, ))
param_list = set(param_list)
image = cv2.imread('./images/69.jpg', cv2.IMREAD_GRAYSCALE)
cal_v3(param_list, image)

[[0.98050735 0.98050735 0.97084724 ... 0.78105119 0.78105119 0.78105119]
 [0.95169891 0.94221045 0.93277898 ... 0.70718328 0.70718328 0.70718328]
 [0.90482535 0.89562068 0.86834469 ... 0.63767378 0.63767378 0.63767378]
 ...
 [0.80665753 0.80665753 0.80665753 ... 0.91408655 0.91408655 0.91408655]
 [0.74767729 0.74767729 0.74767729 ... 0.798067   0.798067   0.798067  ]
 [0.85044122 0.85044122 0.85044122 ... 0.62281016 0.62281016 0.62281016]]


In [103]:
param_list = []
param_list.append((1, ))
param_list.append((0.3, ))
param_list.append((0.6, ))
param_list = set(param_list)

image = cv2.imread('./images/test.png', cv2.IMREAD_GRAYSCALE)
cal_v3(param_list, image)

In [28]:
def cal_v4(param_list: list, image, origin_name, extension):
  """伽马变换"""
  # cv2.imshow('origin', image)
  cv2.imwrite(f'output/{origin_name}_origin{extension}', image)
  for param in param_list:
    fI = image / 255.0
    gamma = param[0] # 0.3
    O = np.power(fI, gamma)
    # cv2.imshow(f'gamma: {gamma}', O)
    # need to extent to unit8
    O = O * 255
    filename = f"output/{origin_name}_{str(gamma).replace('.', '_')}{extension}"
    status = cv2.imwrite(filename, O)
  cv2.waitKey()
  cv2.destroyAllWindows()

In [29]:
param_list = []
param_list.append((2.5, ))
# param_list.append((1, ))
param_list = set(param_list)
filename = '69'
extension = '.jpg'
image = cv2.imread(f'./images/{filename}{extension}', cv2.IMREAD_GRAYSCALE)
cal_v4(param_list, image, filename, extension)